before_script:
  - cd vendmachtrack/
  - mvn clean install -DskipTests -Dfindbugs.skip

stages:
  - build
  - lint
  - test
  - coverage-report

build:
  stage: build
  image: maven:3.9.4-amazoncorretto-20
  script:
    - mvn compile
  only:
    - merge_requests

checkstyle:
  stage: lint
  image: maven:3.9.4-amazoncorretto-20
  script:
    - mvn checkstyle:checkstyle -Dcheckstyle.failOnViolation=true
  only:
    - merge_requests
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/vendmachtrack/test-results/checkstyle/*.xml
  needs:
    - build

spotbugs:
  stage: lint
  image: maven:3.9.4-amazoncorretto-20
  script:
    - mvn com.github.spotbugs:spotbugs-maven-plugin:check
  only:
    - merge_requests
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/vendmachtrack/test-results/spotbugs/**/spotbugs.xml
  needs:
    - build

test: 
  stage: test
  image: maven:3.9.4-amazoncorretto-20
  script:
    - mvn test
  only:
    - merge_requests
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/vendmachtrack/test-results/junit/**/*
  needs:
    - build

verify:
  stage: coverage-report
  image: maven:3.9.4-amazoncorretto-20
  script:
    - mvn verify
    - cat $CI_PROJECT_DIR/vendmachtrack/test-results/jacoco/index.html | grep -o 'Total[^%]*%'
  coverage: '/<td class="ctr2">(\d+%)/'
  only:
    - merge_requests
  artifacts:
    when: always
    paths:
      - vendmachtrack/test-results/jacoco
  needs:
    - build
    - checkstyle
    - spotbugs
    - test